dist: trusty
sudo: require

language: cpp
compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - cmake
      - libgoogle-glog-dev
      - libgflags-dev
      - git

before_install:
  - sudo apt install -y sqlite3 libvsqlitepp-dev uuid uuid-dev libmemcached-dev libpqxx-dev sshfs libc6-pic librabbitmq-dev
  - export CXX=g++-6
  - export CC=gcc-6
  - git clone https://github.com/python/cpython
  - cd cpython && git checkout 3.6 && ./configure --prefix=/usr && make -j 2 && sudo make install && cd -
  - git clone https://github.com/facebook/proxygen
  - sudo ./proxygen/proxygen/deps.sh
  - git clone https://github.com/antlr/antlr4
  - cd antlr4/runtime/Cpp
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_INSTALL_PREFIX=/usr ..
  - make -j 2
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

script:
  - git submodule update --init --recursive
  - mkdir -p build && cd build && cmake -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 .. && make -j 2
