dist: trusty
sudo: require

language: cpp
compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - cmake
      - libgoogle-glog-dev
      - libgflags-dev
      - git

before_install:
  - sudo apt install -y sqlite3 python3 python3-dev libvsqlitepp-dev uuid uuid-dev libmemcached-dev libpqxx-dev sshfs libc6-pic
  - git clone https://github.com/antlr/antlr4
  - cd /antlr4/runtime/Cpp \
  - mkdir -p build \
  - cd build \
  - cmake .. \
  - make -j 4 \
  - make install \
  - rm -fr /antlr4
  - git clone https://github.com/facebook/proxygen
  - ./proxygen/proxpgen/deps.sh
  - cd $TRAVIS_BUILD_DIR

script:
  - git submodule update --init --recursive
  - mkdir -p build && cd build && cmake .. && make -j 2
