FROM quicksave/dev-antlr

RUN git clone https://github.com/python/cpython \
    && cd cpython \
    && git checkout 3.6 \
    && export CC=gcc \
    && export CXX=g++ \
    && ./configure \
    && make -j 4 \
    && make install \
    && cd .. \
    && rm -fr cpython

RUN apt-get install -y virtualenv python-pip

RUN pip install --upgrade pip

RUN virtualenv -p python3.6 venv
