FROM quicksave/dev-ssh

COPY qs-audit /usr/bin/qs-audit

RUN git clone https://github.com/curl/curl \
    && mkdir -p curl/build \
    && cd curl/build \
    && export CC=gcc-5 \
    && export CXX=g++-5 \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr .. \
    && make -j 4 \
    && make install \
    && cd - \
    && rm -fr curl

