FROM quicksave/dev-libs

RUN apt-get install -y libsqlite3-dev libpq-dev postgresql-server-dev-all

RUN apt-get install -y libssl1.0-dev

RUN pip install pyparsing

RUN git clone --recursive https://github.com/adiog/io_quicksave_cpp \
    && mkdir build \
    && cd build \
    && cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release ../io_quicksave_cpp \
    && make -j 4
