FROM quicksave/bin

RUN mkdir -p /keys
RUN mkdir -p /sshfs

RUN apt-get install virtualenv sshfs -y

RUN virtualenv -p python3.6 venv \
    && . venv/bin/activate \
    && pip3 install git+https://github.com/adiog/io_quicksave_pybeans \
    && pip3 install git+https://github.com/adiog/io_quicksave_api-ext

COPY storage_id_rsa /
COPY storage_id_rsa.pub /

CMD . venv/bin/activate \
    && mkdir ~/.ssh \
    && mkdir -p /storage \
    && ssh-keyscan storage_quicksave_docker >> ~/.ssh/known_hosts \
    && sshfs storage_quicksave_docker:/storage /storage/ -o IdentityFile=/storage_id_rsa -o idmap=user  \
    && export LD_LIBRARY_PATH=/usr/local/lib \
    && export GLOG_logtostderr=1 \
    && export IO_QUICKSAVE_MQ_HOST=mq_quicksave_docker \
    && ./build/api \
        --IO_QUICKSAVE_MEMCACHED_HOST=mem_quicksave_docker \
        --IO_QUICKSAVE_MEMCACHED_PORT=11211 \
        --IO_QUICKSAVE_MQ_HOST=mq_quicksave_docker \
        --IO_QUICKSAVE_MQ_PORT=5672 \
        --IO_QUICKSAVE_MASTER_DATABASE_CONNECTION_STRING="sqlite:///storage/master.db"
