FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y openssh-server

RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN mkdir -p /root/.ssh
RUN mkdir -p /var/run/sshd

CMD /usr/sbin/sshd -D